buzzwords = [
    'ARR',
    'Advocacy',
    'Agile',
    'Appium',
    'Awareness',
    'Benchmarks',
    'Big Data',
    'Blog',
    'Business Development',
    'CI / CD',
    'Churn',
    'Cloud',
    'Concurrency',
    'Content',
    'Developer Community',
    'Devops',
    'Ecosystem',
    'Enterprise',
    'Evangelism',
    'Evangelist',
    'Execution',
    'Extensibility',
    'Fast Waterfall',
    'Fundraise',
    'Headcount',
    'Investor',
    'Lead Generation',
    'Learnings',
    'Mobile Market',
    'Platform',
    'Portal',
    'Professional Services',
    'Renewals',
    'Scalibility',
    'Shu-Ha-Ri',
    'Strategic',
    'Swim Lane',
    'Thought Leadership',
    'Value Proposition',
    'White Paper'
]
