buzzwords = [
    "devops",
    "agile",
    "value proposition",
    "ARR",
    "Blog",
    "Execution",
    "Churn",
    "Investor",
    "Renewals",
    "Professional Services",
    "Strategic",
    "Business Development",
    "Appium",
    "Enterprise",
    "Mobile Market",
    "Learnings",
    "Awareness",
    "Content",
    "Lead Generation",
    "Advocacy",
    "Thought Leadership",
    "Developer Community",
    "White Paper",
    "Big Data",
    "Fast Waterfall",
    "Evangelist",
    "Swim Lane",
    "Platform",
    "Portal",
    "Ecosystem",
    "Evangelism",
    "Extensibility",
    "Scalibility",
    "Concurrency",
    "CI / CD",
    "Cloud",
    "Shu-Ha-Ri",
    "Fundraise",
    "Benchmarks",
    "Headcount"]
